FROM sspreitzer/shellinabox 
RUN sudo apt-get update && sudo apt-get install -y vim nano \ 
net-tools iputils-ping telnet tcpdump nmap  ssh fping dsniff ftp \ 
gcc make build-essential bsdmainutils hydra john
